// Coverage registry for the Lottie format (issue #138, epic #137).
//
// Every property key the official Lottie schema defines is listed here with a
// disposition: it is either `modeled` (the typed model decodes it) or
// `reported` (recognized but recorded as unsupported, never silently dropped).
// A meta-test asserts this registry's key set equals the pinned schema's key set,
// so "validation is complete over the input model" (rule C6) is a build-gated
// theorem rather than a claim: adding or removing a schema key fails the test
// until the registry is updated.
//
// The authoritative key list is pinned in the test from `lottie/lottie-spec`
// (regenerated by docs/lottie-format/verify-coverage.sh). This registry covers
// the official spec; the larger lottie-web/bodymovin superset (layer styles,
// effects, expressions, ...) is handled as report-only by the importer and is
// documented in docs/lottie-format/lottie-import-mapping.md.

public enum LottieFeatureCoverage {
    /// How the model treats a given schema key.
    public enum Disposition: Equatable, Sendable {
        /// Decoded into a typed home in the model.
        case modeled
        /// Recognized but recorded as unsupported; never silently dropped.
        case reported
    }

    /// Every official-spec property key with its disposition. The meta-test
    /// (`LottieFeatureCoverageTests`) checks this set against the pinned schema.
    public static let registry: [String: Disposition] = [
        // Document / animation
        "v": .modeled, "ver": .modeled, "fr": .modeled, "ip": .modeled,
        "op": .modeled, "w": .modeled, "h": .modeled, "nm": .modeled,
        "assets": .modeled, "layers": .modeled, "markers": .reported,
        "meta": .reported, "custom": .reported,
        // Slots are not yet implemented: recognized and reported, not dropped.
        "slots": .reported, "sid": .reported,
        // Assets
        "id": .modeled, "refId": .modeled, "u": .modeled, "e": .modeled,
        // Layers
        "ty": .modeled, "hd": .modeled, "ind": .modeled, "parent": .modeled,
        "ks": .modeled, "ao": .modeled, "tt": .modeled, "tp": .modeled,
        "masksProperties": .modeled, "bm": .modeled, "sr": .modeled,
        "st": .modeled, "tm": .modeled, "sw": .modeled, "sh": .modeled,
        "sc": .modeled, "shapes": .modeled,
        // Transform
        "a": .modeled, "p": .modeled, "r": .modeled, "s": .modeled,
        "o": .modeled, "sk": .modeled, "sa": .modeled,
        // Shapes (styles, geometry, modifiers)
        "c": .modeled, "lc": .modeled, "lj": .modeled, "ml": .modeled,
        "ml2": .modeled, "d": .modeled, "g": .modeled, "np": .modeled,
        "it": .modeled, "pt": .modeled, "ir": .modeled, "is": .modeled,
        "or": .modeled, "os": .modeled, "sy": .modeled, "m": .modeled,
        // Stroke dash
        "n": .modeled,
        // Properties / keyframes (e = keyframe end shares the asset-embedded key
        // string; one entry covers the string. x/y = easing-handle components.)
        "k": .modeled, "t": .modeled, "i": .modeled, "to": .modeled,
        "ti": .modeled, "x": .modeled, "y": .modeled,
        // Masks
        "mode": .modeled,
        // Markers
        "cm": .reported, "dr": .reported,
    ]
}
